class_name CharacterStateFactory
extends RefCounted

func create(id: int, root: Node3D, visual_root: Node3D, cell: Vector2i, ai: bool, style: String) -> CharacterState:
	return CharacterState.new({
		"id": id,
		"node": root,
		"visual_node": visual_root,
		"grid_pos": cell,
		"alive": true,
		"hp": Constants.PLAYER_MAX_HP,
		"max_hp": Constants.PLAYER_MAX_HP,
		"downed": false,
		"downed_timer": 0.0,
		"is_moving": false,
		"move_tween": null,
		"move_from_cell": cell,
		"move_target_cell": cell,
		"move_target_world": Vector3.ZERO,
		"move_speed_world": 0.0,
		"grid_motion_active": false,
		"speed": 5,
		"bomb_max": 1,
		"bomb_range": 2,
		"shield": 0,
		"shield_timer": 0.0,
		"suit": style,
		"lava_time": 0.0,
		"lava_eruption_time": 0.0,
		"airborne": false,
		"vertical_velocity": 0.0,
		"airborne_stomped": {},
		"status": "Ready",
		"consumables": [],
		"selected_consumable_index": 0,
		"invincible_timer": 0.0,
		"wings_timer": 0.0,
		"football_timer": 0.0,
		"slow_timer": 0.0,
		"prison_timer": 0.0,
		"fire_exposure_time": 0.0,
		"bomb_placed_count": 0,
		"ai": ai,
		"move_timer": 0.0,
		"move_interval": randf_range(0.3, 0.8),
		"bomb_timer": 0.0,
		"bomb_interval": randf_range(1.5, 3.5),
		"move_dir": Vector2i.ZERO,
		"last_bomb_pos": Vector2i(-1, -1),
		"last_bomb_place_time": -99.0,
		"bomb_hop_until": -99.0,
		"bomb_hop_cells": {},
		"last_move_dir": Vector2i.DOWN,
		"elevated_cell": Vector2i(-1, -1),
		"wall_stay_timer": 0.0,
		"wall_warning": false,
		"impact_support": false,
		"impact_support_timer": 0.0,
		"impact_support_cracks": null,
		"last_seen_player_pos": Vector2i(-1, -1),
		"lava_flight_available": false,
		"lava_flight_target": Vector2i(-1, -1),
		"boss_id": "",
		"boss_name": "",
		"is_minion": false,
		"skill_interval": 0.0,
		"skill_timer": 0.0,
		"frozen_timer": 0.0,
		"duel_pending": false,
		"duel_return_grace": 0.0,
	})
